version: 2
updates:
  - package-ecosystem: github-actions
    commit-message:
      prefix: deps(actions)
    directory: /
    labels:
      - automated
      - dependencies
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    commit-message:
      prefix: deps(service-status)
    directory: /modules/packages/by_name/service_status/src
    labels:
      - automated
      - dependencies
    schedule:
      interval: weekly
  - package-ecosystem: nix
    commit-message:
      prefix: deps(flake)
    directory: /
    labels:
      - automated
      - dependencies
    schedule:
      day: friday
      interval: weekly
    groups:
      development:
        patterns:
          - devenv
      flake:
        patterns:
          - files
          - flake-parts
          - import-tree
          - nixpkgs
          - treefmt-nix
      home-manager:
        patterns:
          - home-manager
          - nixvim
          - snekcheck
          - stylix
      infrastructure:
        patterns:
          - terranix
      nixos:
        patterns:
          - determinate
          - disko
          - nixos-hardware
