version: 2
updates:
  - package-ecosystem: github-actions
    commit-message:
      prefix: deps
    directory: /
    labels:
      - automated
      - dependencies
      - github-actions
    schedule:
      interval: weekly
  - package-ecosystem: nix
    commit-message:
      prefix: deps
    directory: /
    labels:
      - automated
      - dependencies
    schedule:
      day: friday
      interval: weekly
    groups:
      development:
        patterns:
          - devenv
          - justix
      flake:
        patterns:
          - files
          - flake-parts
          - import-tree
          - nixpkgs
          - treefmt-nix
      home-manager:
        patterns:
          - home-manager
          - nixvim
          - snekcheck
          - stylix
      infrastructure:
        patterns:
          - terranix
      nixos:
        patterns:
          - determinate
          - disko
          - nixos-hardware
