keys:
  - &ares age1f5782dgrzyx4hgtkg49s2kuwquqmsazjaravx09sgg76kxf80qnqmmrjjq
  - &global age1lpsq0vlmf8mxg9ycumq6msczl3x9k5cfrag4q04kq20wqqkedq6qq36xxs
creation_rules:
  - path_regex: cfg/nixos/ares/secrets/[^/]+\.env$
    format: dotenv
    key_groups:
      - age:
          - *ares
          - *global
  - path_regex: cfg/nixos/ares/secrets/[^/]+\.yaml$
    format: yaml
    key_groups:
      - age:
          - *ares
          - *global
