{
  libretro-shaders-slang,
  writeText,
}:
writeText "gba.slangp" ''
  shaders = "4"
  feedback_pass = "0"

  shader0 = "${libretro-shaders-slang}/share/libretro/shaders/shaders_slang/handheld/shaders/color/lut/GBA-LUT.slang"
  alias0 = ""
  wrap_mode0 = "clamp_to_border"
  mipmap_input0 = "false"
  filter_linear0 = "false"
  float_framebuffer0 = "false"
  srgb_framebuffer0 = "false"
  scale_type_x0 = "source"
  scale_x0 = "1.000000"
  scale_type_y0 = "source"
  scale_y0 = "1.000000"

  shader1 = "${libretro-shaders-slang}/share/libretro/shaders/shaders_slang/handheld/shaders/lcd-cgwg/lcd-grid-v2.slang"
  alias1 = ""
  wrap_mode1 = "clamp_to_border"
  mipmap_input1 = "false"
  filter_linear1 = "false"
  float_framebuffer1 = "false"
  srgb_framebuffer1 = "false"
  scale_type_x1 = "viewport"
  scale_x1 = "1.000000"
  scale_type_y1 = "viewport"
  scale_y1 = "1.000000"

  shader2 = "${libretro-shaders-slang}/share/libretro/shaders/shaders_slang/handheld/shaders/color/gba-color.slang"
  alias2 = ""
  wrap_mode2 = "clamp_to_border"
  mipmap_input2 = "false"
  filter_linear2 = "false"
  float_framebuffer2 = "false"
  srgb_framebuffer2 = "false"
  scale_type_x2 = "source"
  scale_x2 = "1.000000"
  scale_type_y2 = "source"
  scale_y2 = "1.000000"

  shader3 = "${libretro-shaders-slang}/share/libretro/shaders/shaders_slang/handheld/shaders/pixel_transparency.slang"
  alias3 = ""
  wrap_mode3 = "clamp_to_border"
  mipmap_input3 = "false"
  filter_linear3 = "false"
  float_framebuffer3 = "false"
  srgb_framebuffer3 = "false"
  scale_type_x3 = "viewport"
  scale_x3 = "1.000000"
  scale_type_y3 = "viewport"
  scale_y3 = "1.000000"

  gamma = "3.500000"
  blacklevel = "0.000000"
  BGR = "1.000000"
  textures = "SamplerLUT1;SamplerLUT2"
  SamplerLUT1 = "${libretro-shaders-slang}/share/libretro/shaders/shaders_slang/handheld/shaders/color/lut/gba-grey1.png"
  SamplerLUT1_mipmap = "false"
  SamplerLUT1_wrap_mode = "clamp_to_border"
  SamplerLUT2 = "${libretro-shaders-slang}/share/libretro/shaders/shaders_slang/handheld/shaders/color/lut/gba-grey2.png"
  SamplerLUT2_mipmap = "false"
  SamplerLUT2_wrap_mode = "clamp_to_border"
''
