import = ["/home/jtrrll/.config/alacritty/vscode-dark-plus.toml"]

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[window.padding]
x = 8
y = 8
