name: ci

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint with ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0

  rust-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: programs/rust
    steps:
      - name: Install dependencies
        run: sudo apt install libdbus-1-dev pkg-config
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: cargo test
