---
name: misc-ci

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "*" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: programs/rust
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install libdbus-1-dev pkg-config
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: cargo test
  shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint with ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0

...
